#!/usr/bin/env python3
"""
Bakes a land/sea bitmask into src/landMask.ts.

The globe needs to show real geography so its pins land on the right
continents. Shipping polygon outlines would mean carrying a GeoJSON and a
point-in-polygon test into the browser; rasterising once at build time to a
1-degree grid gives the same answer in a lookup, and compresses to a few kB.

Run only when the resolution needs to change:
    python3 scripts/build-land-mask.py
"""

import base64
import json
import urllib.request
from pathlib import Path

from PIL import Image, ImageDraw

SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
    "master/geojson/ne_110m_land.geojson"
)
WIDTH, HEIGHT = 360, 180  # one cell per degree
OUT = Path(__file__).resolve().parent.parent / "src" / "landMask.ts"


def to_pixels(ring):
    """Equirectangular projection: lon -180..180 -> 0..W, lat 90..-90 -> 0..H."""
    return [
        ((lon + 180.0) / 360.0 * WIDTH, (90.0 - lat) / 180.0 * HEIGHT)
        for lon, lat in ring
    ]


def main():
    print(f"fetching {SOURCE}")
    with urllib.request.urlopen(SOURCE) as response:
        data = json.load(response)

    image = Image.new("1", (WIDTH, HEIGHT), 0)
    draw = ImageDraw.Draw(image)

    for feature in data["features"]:
        geometry = feature["geometry"]
        polygons = (
            [geometry["coordinates"]]
            if geometry["type"] == "Polygon"
            else geometry["coordinates"]
        )
        for polygon in polygons:
            # Ring 0 is the outline; any that follow are holes (inland seas).
            draw.polygon(to_pixels(polygon[0]), fill=1)
            for hole in polygon[1:]:
                draw.polygon(to_pixels(hole), fill=0)

    pixels = image.load()
    bits = bytearray((WIDTH * HEIGHT + 7) // 8)
    land = 0
    for y in range(HEIGHT):
        for x in range(WIDTH):
            if pixels[x, y]:
                index = y * WIDTH + x
                bits[index >> 3] |= 0x80 >> (index & 7)
                land += 1

    encoded = base64.b64encode(bytes(bits)).decode("ascii")
    coverage = land / (WIDTH * HEIGHT) * 100

    OUT.write_text(
        f'''/**
 * Land/sea mask, {WIDTH}x{HEIGHT} at one cell per degree, packed one bit per
 * cell and base64'd. About {coverage:.0f}% of the grid is land, which is the
 * figure you'd expect once Antarctica is included.
 *
 * Generated by scripts/build-land-mask.py from Natural Earth 110m land — do
 * not edit by hand. Rasterising at build time keeps a GeoJSON and a
 * point-in-polygon test out of the bundle; this is a lookup.
 */

export const LAND_MASK_WIDTH = {WIDTH}
export const LAND_MASK_HEIGHT = {HEIGHT}

const PACKED =
  '{encoded}'

const bits = Uint8Array.from(atob(PACKED), (c) => c.charCodeAt(0))

/** True where the given coordinate falls on land. */
export function isLand(lat: number, lon: number) {{
  const x = Math.min(
    LAND_MASK_WIDTH - 1,
    Math.max(0, Math.floor(((lon + 180) / 360) * LAND_MASK_WIDTH)),
  )
  const y = Math.min(
    LAND_MASK_HEIGHT - 1,
    Math.max(0, Math.floor(((90 - lat) / 180) * LAND_MASK_HEIGHT)),
  )
  const index = y * LAND_MASK_WIDTH + x
  return (bits[index >> 3] & (0x80 >> (index & 7))) !== 0
}}
''',
        encoding="utf8",
    )

    print(f"wrote {OUT.relative_to(Path.cwd())}")
    print(f"  {len(bits)} bytes packed -> {len(encoded)} base64 chars")
    print(f"  land coverage {coverage:.1f}%")


if __name__ == "__main__":
    main()
